### PR TITLE
Add page application and initial urls route

### PR DESCRIPTION
**Pull request by maximest-pierre**

### CODE REVIEW

**Comment by maximest-pierre** [comment]
lgtm

**Comment by gzsierra** [comment]
remove unchange file please

**Comment by maximest-pierre** [comment]
These are init.py so they are empty but python/django need them to work so they must stay there :smile:

**Comment by gzsierra** [comment]
Are they necessary in the commit ?

**Comment by maximest-pierre** [comment]
Yeah or else the application will fail

**Comment by gzsierra** [comment]
Yeaaahh I see 
lgtm
:rocket:

**Comment by maximest-pierre** [comment]
:dog2:

**Pull request merged**
